# -*- coding: utf-8 -*-
"""Sales_Trend_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vkfs1Mgj4YWyMnTT7JOwKQ7UKIdOpJ65

DATA IMPORT
"""

import pandas as pd

df = pd.read_csv("/content/Superstore Sales Datasets.csv", encoding='latin1')

print(df.head())

"""Understand the DATASET"""

print(df.shape)

print(df.columns)

print(df.info())

print(df.describe())

"""DATA CLEANING

"""

print(df.isnull().sum())

from google.colab import drive
drive.mount('/content/drive')

print(df.duplicated().sum())

df.drop('Postal Code', axis=1, inplace=True)

print(df.isnull().sum())

"""CONVERT Order_Date in Date Format"""

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

df['Month'] = df['Order Date'].dt.month_name()

df['Year'] = df['Order Date'].dt.year

print(df['Order Date'].head())

"""ANALYSIS

MONTHLY SALES TREND
"""

month_order = ['January','February','March','April',
               'May','June','July','August',
               'September','October','November','December']

monthly_sales = df.groupby('Month')['Sales'].sum().reindex(month_order)

print(monthly_sales)

monthly_sales.plot(kind='line', marker='o', figsize=(10,5))

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.xticks(rotation=45)

plt.show()

"""## Insights: Monthly Sales Trend

- The lowest sales were recorded in February, with sales around 60,000, indicating a weak sales period during the beginning of the year.

- Sales increased significantly in March, showing a sharp recovery compared to February.

- From April to August, sales remained relatively stable, ranging between approximately 140,000 and 160,000.

- A major growth in sales was observed in September, where sales crossed 300,000, indicating a high-demand period.

- After a slight decline in October, the highest sales were achieved in November, reaching nearly 350,000.

- December also recorded strong sales performance, remaining above 320,000.

- Overall, the analysis indicates that sales tend to increase during the end of the year, suggesting the impact of festive seasons, promotional campaigns, or increased customer demand.

YEAR-WISE SALES
"""

yearly_sales = df.groupby('Year')['Sales'].sum()

print(yearly_sales)

yearly_sales.plot(kind='bar')

plt.title("Year-wise Sales")

plt.ylabel("Sales")

plt.show()

"""## Insights: Year-wise Sales Analysis

- The sales performance showed a slight decline from 2015 to 2016, decreasing from approximately 480,000 to 460,000.

- A significant growth in sales was observed in 2017, where total sales increased to around 600,000.

- The highest sales were recorded in 2018, reaching approximately 720,000, indicating strong business growth.

- The continuous increase in sales from 2016 to 2018 suggests improved market performance and increasing customer demand.

- The overall trend indicates that the company experienced substantial sales growth over the years.

CATEGORY-WISE SALES
"""

category_sales = df.groupby('Category')['Sales'].sum()

print(category_sales)

category_sales.plot(kind='bar')

plt.title("Category-wise Sales")

plt.ylabel("Sales")

plt.show()

"""## Insights: Category-wise Sales Analysis

- Technology category generated the highest sales, exceeding approximately 820,000, making it the best-performing category.

- Furniture category recorded sales of around 730,000, showing strong customer demand.

- Office Supplies generated the lowest sales among the three categories, with approximately 700,000 in total sales.

- Although the difference between Furniture and Office Supplies was relatively small, Technology maintained a clear lead.

- The findings suggest that customers spend more on technology products, highlighting their importance in overall business revenue.

SUB-CATEGORY ANALYSIS
"""

sub_sales = df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)

print(sub_sales)

sub_sales.plot(kind='bar', figsize=(12,5))

plt.title("Sub-Category Sales")

plt.show()

"""## Insights: Sub-Category Sales Analysis

- Phones emerged as the highest-selling sub-category, generating sales of more than 330,000.

- Chairs ranked second in terms of sales performance, contributing approximately 320,000 in total sales.

- Storage, Tables, and Binders also performed well, indicating consistent customer demand.

- Fasteners recorded the lowest sales among all sub-categories, contributing only a small portion to total revenue.

- Labels and Envelopes also generated relatively low sales compared to other product groups.

- The significant variation in sales across sub-categories highlights differences in customer preferences and purchasing behavior.

- High-performing sub-categories such as Phones and Chairs should receive greater focus in inventory planning and promotional activities.

REGION-WISE SALES
"""

region_sales = df.groupby('Region')['Sales'].sum()

print(region_sales)

region_sales.plot(kind='bar')

plt.title("Region-wise Sales")

plt.ylabel("Sales")

plt.show()

"""## Insights: Region-wise Sales Analysis

- West region generated the highest sales, reaching approximately 710,000, making it the top-performing region.

- East region recorded sales of around 670,000, indicating strong market performance and customer demand.

- Central region achieved sales of nearly 490,000, placing it in the middle of the overall regional ranking.

- South region generated the lowest sales, with approximately 390,000 in total sales.

- The gap between the highest-performing region (West) and the lowest-performing region (South) is significant, highlighting regional disparities in sales performance.

- West and East regions together contributed the majority of total sales, demonstrating their importance to overall business revenue.

- The comparatively lower sales in the South region suggest opportunities for targeted marketing campaigns, improved distribution strategies, and customer engagement initiatives.

- The analysis indicates that strengthening performance in lower-performing regions could help achieve a more balanced and sustainable sales distribution across all regions.

SEGMENT-WISE SALES
"""

segment_sales = df.groupby('Segment')['Sales'].sum()

print(segment_sales)

segment_sales.plot(kind='pie', autopct='%1.1f%%')

plt.title("Segment-wise Sales")

plt.ylabel("")

plt.show()

"""## Insights: Segment-wise Sales Analysis

- The Consumer segment contributed the highest share of total sales, accounting for approximately 50.8% of overall revenue.

- Corporate customers generated around 30.4% of total sales, making it the second-largest revenue-contributing segment.

- The Home Office segment contributed approximately 18.8% of total sales, representing the smallest share among all customer segments.

- More than half of the company's sales originated from the Consumer segment, highlighting its importance as the primary customer base.

- The significant difference between the Consumer and Home Office segments indicates varying purchasing behaviors and market demand across customer groups.

- The Corporate segment maintained a strong contribution, suggesting consistent demand from business customers and organizations.

- The relatively lower contribution from the Home Office segment presents an opportunity for targeted marketing campaigns and product offerings to increase engagement and sales.

- The analysis suggests that while the business is heavily reliant on Consumer sales, strengthening Corporate and Home Office segments could help diversify revenue sources and improve overall business stability.

# Conclusion

The Sales Trend Visualization project successfully analyzed historical sales data to identify important business patterns and customer preferences.

The analysis revealed that sales performance improved significantly during the latter part of the year, with November recording the highest monthly sales, while February showed the lowest sales performance.

Year-wise analysis indicated a positive growth trend, with 2018 emerging as the best-performing year and demonstrating continuous business expansion after 2016.

Among the product categories, Technology generated the highest sales, highlighting its major contribution to overall revenue. Furniture and Office Supplies also contributed significantly to total sales.

Sub-category analysis showed that Phones and Chairs were the strongest revenue-generating products, whereas Fasteners, Labels, and Envelopes recorded the lowest sales.

Overall, the findings suggest that understanding sales trends and customer preferences can help organizations make informed decisions related to inventory management, marketing strategies, and resource allocation. Data visualization proved to be an effective tool for transforming raw sales data into meaningful business insights.
"""